### PR TITLE
Refactor helm artifacts publish flow

### LINKED ISSUE #458: Refactor helm artifacts publishing
### Is this the right place to submit this?

- [X] This is not a question about how to use the sail-operator

### Feature Description

Refactor the flow of helm artifacts publishing to the following:
- Check for latest published artifacts assets and compare it to published helm artifacts version.
- Create a scheduled cron based github action job to check for the changes and decide if needs to published.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MaxBab**
#### What type of PR is this?

- [ ] Enhancement / New Feature
- [ ] Bug Fix
- [X] Refactor
- [ ] Optimization
- [ ] Test
- [ ] Documentation Update

#### What this PR does / why we need it:
Refactor the helm artifacts publish flow to continuously (cron job) check for the published helm artifacts according to latest release assets.
If missing, update and add a release to the "index.yaml" file under "gh-pages" branch.
If exists, do not perform any change.

#### Which issue(s) this PR fixes:

Fixes #458

### CODE REVIEW

**Review by dgn — APPROVED** [review]
Nice work!

**Comment by dgn** [comment]
adding /hold so Brian can take a look

**Comment by dgn** [comment]
ah too late

**Comment by MaxBab** [comment]
Thanks.
If Brian will have some comments or suggestion to modify, I'll do it in another PR.

**Comment by bmangoen** [comment]
Great work ! All good for me

**Pull request merged**
